apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-hello-world-html
  labels:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <title>Hello</title>
    </head>
    <body>
      <h1>{{ .Values.pageTitle }}</h1>
    </body>
    </html>
