FROM python:3.12-slim

WORKDIR /app

# Не ставим лишние пакеты
# Секреты передаем при запуске контейнера

COPY README.md /app/README.md

# Оставляем только нужный порт
EXPOSE 8080

CMD ["python", "-m", "http.server", "8080"]
